spring.application.name=spring-api-rest-1


spring.datasource.url=jdbc:mysql://localhost:3306/negocios2026?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
